name: CI Pipeline

on:
  push:
    branches:
      - main
      - docker-setup
  pull_request:
    branches:
      - main
  workflow_dispatch:       # <--- Added this to allow manual runs

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8

      - name: Run linter
        run: flake8 .

      - name: Run tests
        run: pytest

  docker-build:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t motivational-quotes-api .
